### PR TITLE
Adds a check that makes a simple request to check connection to db

### PR DESCRIPTION
**Pull request by Illizian**
This is a concept PR to open up discussions regarding checking that the URI resolves.

This adds a very basic request to the main endpoint, which is checked for ```err```'s. Additionally, we could check the response received and possibly headers to further ensure we can not only make a connection but have made it to an actual Neo4j server.

Thoughts?

### CODE REVIEW

**Comment by Illizian** [comment]
Build broken as a result of no Neo4j instance on Codeship.

**Comment by domdavis** [comment]
Not keen on this. By binding the test directly to the creation of the Neo4j object you've not got a tight coupling with Neo4j existing (hence the broken build) and can't unit test in isolation.

**Comment by domdavis** [comment]
Also, I'd use a different endpoint - The transactional endpoint will create a new transaction which will be left open. http://neo4j.com/docs/stable/rest-api-security.html has some better endpoints to hit. If we're going to do the test connection I'd probably add the ability to check if the username and password has been reset and an optional callback to deal with it if it isn't.

Since the DB can disappear once we've connected to it my personal preference would be to not bother with the test and just handle failures in the client code when transactions are called.

**Comment by Illizian** [comment]
After discussion we're opting to add a method to ping the server and check the connection.

**Pull request closed without merging**
